# FOR UNO
BOARD := arduino:avr:uno

# FOR TINY
# BOARD := attiny:avr:ATtinyX5:cpu=attiny85,clock=internal8

# common options
LIBRARY_PATH := ../ArduinoTools

ARDDUDE_OPTIONS := -l cr -o raw -d
PORT := /dev/ttyUSB0

ARDUINO_CLI_UPLOAD_OPTS=-v
ARDUINO_CLI_COMPILE_OPTS=--warnings all --build-property "build.extra_flags=-DREDUCED_MAP -DIR_REMOTE_NETGEM"
