# FOR UNO
#BOARD := arduino:avr:uno

# FOR NANO
BOARD := arduino:avr:nano:cpu=atmega328isp
UPLOAD_PORT := /dev/ttyACM0
BAUDRATE=115200 # 19200

# common options
LIBRARY_PATH := ../ArduinoTools ../ArduinoLibs

ARDDUDE_OPTIONS := -l cr -o raw -d
PORT := /dev/ttyUSB0

ARDUINO_CLI_UPLOAD_OPTS=-v
ARDUINO_CLI_COMPILE_OPTS=--warnings all --build-property "build.extra_flags=-DUSER_FONT -DIR_REMOTE_NETGEM"
